export const ExclusiveData = [
  {
    id: 1,
    img: require("../assets/images/instamart/ferrero.png"),
    title: "Ferrero Rocher",
    old: "₹100",
    new: "₹80",
    offer: "20%",
  },
  {
    id: 2,
    img: require("../assets/images/instamart/shots.png"),
    title: "Cadbury Shots",
    old: "₹300",
    new: "₹180",
    offer: "25%",
  },
  {
    id: 3,
    img: require("../assets/images/instamart/good-day.png"),
    title: "Good Day",
    old: "₹100",
    new: "₹70",
    offer: "30%",
  },
  {
    id: 4,
    img: require("../assets/images/instamart/maggie-2.png"),
    title: "Maggie",
    old: "₹70",
    new: "₹50",
    offer: "15%",
  },
  {
    id: 5,
    img: require("../assets/images/instamart/aer.png"),
    title: "Aer Freshner",
    old: "₹100",
    new: "₹50",
    offer: "50%",
  },
  {
    id: 6,
    img: require("../assets/images/instamart/wax.png"),
    title: "Hair Wax",
    old: "₹150",
    new: "₹75",
    offer: "35%",
  },
  {
    id: 7,
    img: require("../assets/images/instamart/almods.png"),
    title: "Almonds",
    old: "₹230",
    new: "₹130",
    offer: "45%",
  },
  {
    id: 8,
    img: require("../assets/images/instamart/sugar.png"),
    title: "Sugar",
    old: "₹170",
    new: "₹50",
    offer: "65%",
  },
  {
    id: 9,
    img: require("../assets/images/instamart/oliv-oil.png"),
    title: "Olive Oil",
    old: "₹650",
    new: "₹577",
    offer: "11%",
  },
  {
    id: 10,
    img: require("../assets/images/instamart/ghee.png"),
    title: "Ghee",
    old: "₹365",
    new: "₹346",
    offer: "5%",
  },
];
