export const FoodCardsData = [
  {
    id: 1,
    img: require("../assets/images/food-card/1.png"),
    title: "The Spice House",
    rating: "4.5",
    time: "30 min",
  },
  {
    id: 2,
    img: require("../assets/images/food-card/2.png"),
    title: "Taste of India",
    rating: "4.2",
    time: "25 min",
  },
  {
    id: 3,
    img: require("../assets/images/food-card/3.png"),
    title: "Go Native",
    rating: "4.7",
    time: "35 min",
  },
  {
    id: 4,
    img: require("../assets/images/food-card/4.png"),
    title: "La Heaven",
    rating: "4.3",
    time: "40 min",
  },
  {
    id: 5,
    img: require("../assets/images/food-card/5.png"),
    title: "Natural Ice Cream",
    rating: "4.6",
    time: "30 min",
  },
  {
    id: 6,
    img: require("../assets/images/food-card/6.png"),
    title: "Kwality Walls",
    rating: "4.4",
    time: "20 min",
  },
  {
    id: 7,
    img: require("../assets/images/food-card/7.png"),
    title: "Domino's Pizza",
    rating: "4.5",
    time: "45 min",
  },
  {
    id: 8,
    img: require("../assets/images/food-card/8.png"),
    title: "KFC",
    rating: "4.2",
    time: "30 min",
  },
  {
    id: 9,
    img: require("../assets/images/food-card/9.png"),
    title: "McDonald's",
    rating: "4.7",
    time: "35 min",
  },
  {
    id: 10,
    img: require("../assets/images/food-card/10.png"),
    title: "Curry House",
    rating: "4.3",
    time: "40 min",
  },
];